# -*- coding: utf-8 -*-
"""yesimaktas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cc3gBZe0gxwaJCoQUUf19lFiPlqK_iqa
"""

import numpy as np
import pandas as pd

from google.colab import files
uploaded=files.upload()

df=pd.read_csv("cities.csv")
df

citiesDataFrame=pd.read_csv("cities.csv", sep=",")
citiesDataFrame.describe()

citiesDataFrame.head()

citiesDataFrame.hist('LatD')

add_row = {'LatD':45, '"LatM"':45, '"LatS"':45,'"NS"':45, '"LonD"':45, '"LonM"':45, '"LonS"':45, '"EW"':'Deneme1', '"City"':'Deneme1', '"State"':'YA'}
citiesDataFrame=citiesDataFrame.append(add_row,ignore_index=True)
citiesDataFrame

print(citiesDataFrame.drop(45))

citiesDataFrame.loc[2]

citiesDataFrame.loc[2]=['7','7','7','Y','7','7','7','G','ANTALYA','A','7','7','7','7','7','7','7','7','7']
citiesDataFrame.loc[2]